verbosity = "info"
max_concurrency = 8
timeout = 20
retry_wait_time = 2
max_retries = 2
exclude = ["mailto:*"]
exclude_path = ["output/ops"]
offline = false
format = "Markdown"
output = "lychee/results.md"
