name: Evidence screenshots

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # nightly at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: screenshots
  cancel-in-progress: true

jobs:
  screenshots:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ensure script permissions
        run: chmod +x scripts/evidence/screenshots.sh

      - name: Capture screenshots
        run: scripts/evidence/screenshots.sh "SCREENSHOTS-CI"

      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-screenshots
          path: output/ops/SCREENSHOTS-*/

      - name: Package latest screenshots
        run: |
          OUTDIR=$(ls -d output/ops/SCREENSHOTS-* | sort | tail -n1)
          echo "Using $OUTDIR"
          tar -czf site-screenshots.tar.gz -C "$OUTDIR" .

      - name: Publish release asset (rolling tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: screenshots-nightly
          name: Screenshots Nightly
          make_latest: true
          prerelease: true
          fail_on_unmatched_files: true
          files: site-screenshots.tar.gz
